language: python
dist: trusty
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -e .[test]"
script:
  - coverage run --source=json_validator setup.py test
after_success:
  coveralls
